apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: infrastructure-base

resources:
- namespaces.yaml
- cluster-issuer.yaml
- ingress.yaml

commonLabels:
  app.kubernetes.io/name: infrastructure
  app.kubernetes.io/component: networking
