apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-articles-service
  namespace: scrollfeed-dev
  labels:
    app: dev-articles-service
    environment: dev
    team: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-articles-service
  template:
    metadata:
      labels:
        app: dev-articles-service
        environment: dev
        team: platform
    spec:
      containers:
      - name: articles-service
        image: justscroll/articles-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
