apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-memes-service
  namespace: scrollfeed-dev
  labels:
    app: dev-memes-service
    environment: dev
    team: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-memes-service
  template:
    metadata:
      labels:
        app: dev-memes-service
        environment: dev
        team: platform
    spec:
      containers:
      - name: memes-service
        image: justscroll/memes-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_URI
        - name: PORT
          value: "8080"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
