apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-service
  labels:
    app: news-service
    component: microservice
    part-of: scrollfeed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: news-service
  template:
    metadata:
      labels:
        app: news-service
        component: microservice
        part-of: scrollfeed
    spec:
      containers:
      - name: news-service
        image: anurag2911/news-service:latest
        imagePullPolicy: Always
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_URI
        - name: NATS_URL
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: NATS_URL
        - name: NEWS_API_KEY
          valueFrom:
            secretKeyRef:
              name: news-api-secret
              key: NEWS_API_KEY
        envFrom:
        - configMapRef:
            name: news-service-config
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
