apiVersion: v1
kind: Service
metadata:
  name: news-service
  labels:
    app: news-service
    component: microservice
    part-of: scrollfeed
spec:
  selector:
    app: news-service
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  type: ClusterIP
