apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-fetcher-service
  namespace: default
  labels:
    app: news-fetcher-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-fetcher-service
  template:
    metadata:
      labels:
        app: news-fetcher-service
    spec:
      containers:
      - name: news-fetcher-service
        image: anurag2911/news-fetcher-service:latest
        imagePullPolicy: Always
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_URI
        - name: NATS_URL
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: NATS_URL
        - name: GNEWS_API_KEY
          valueFrom:
            secretKeyRef:
              name: news-api-secret
              key: GNEWS_API_KEY
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: news-fetcher-service
  namespace: default
spec:
  selector:
    app: news-fetcher-service
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
