apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-fetcher-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: news-fetcher-service
  template:
    metadata:
      labels:
        app: news-fetcher-service
    spec:
      containers:
      - name: news-fetcher-service
        image: news-fetcher-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: MONGO_URI
          value: "mongodb://mongo-service:27017"
        - name: NATS_URL
          value: "nats://nats:4222"
        - name: GNEWS_API_KEY
          valueFrom:
            secretKeyRef:
              name: gnews-secret
              key: api-key
        - name: FETCH_INTERVAL
          value: "4h"
        - name: RATE_LIMIT
          value: "1s"
        - name: MAX_RETRIES
          value: "3"
        - name: RETRY_DELAY
          value: "30s"
        - name: WORKER_COUNT
          value: "3"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Secret
metadata:
  name: gnews-secret
  namespace: default
type: Opaque
data:
  # Replace this with your base64 encoded GNews API key
  api-key: WU9VUl9HTkVXU19BUElfS0VZX0hFUkU=
