apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  labels:
    app: analytics-service
    component: microservice
spec:
  selector:
    app: analytics-service
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP
