apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: scrollfeed-prod

resources:
- ../../../base/news-service

patchesStrategicMerge:
- deployment-patch.yaml

configMapGenerator:
- name: news-service-config
  literals:
  - NEWS_API_BASE_URL=https://newsapi.org/v2/top-headlines
  - NEWS_REGIONS=us,in,de,gb,ca,au,fr,jp
  - NEWS_MAX_PAGES=2
  - NEWS_MAX_ARTICLES=50
  - NEWS_RATE_LIMIT_SECONDS=2
  - NEWS_FETCH_INTERVAL_HOURS=2
  - ENABLE_NATS=true
  - ENABLE_JETSTREAM=true
  - NATS_URL=nats://nats.nats-system.svc.cluster.local:4222
  - NATS_SUBJECT=news.articles.prod
  - LOG_LEVEL=info

secretGenerator:
- name: news-service-secrets
  literals:
  - MONGO_URI=mongodb://mongo-prod.scrollfeed-prod.svc.cluster.local:27017/newsdb-prod
  - NEWS_API_KEY=your-prod-api-key

commonLabels:
  environment: prod
  team: platform

images:
- name: anurag2911/news-service
  newTag: latest

replicas:
- name: news-service
  count: 3
