apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrollfeed-ui
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: scrollfeed-ui
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
