apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-service
  namespace: default
  labels:
    app: news-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: news-service
  template:
    metadata:
      labels:
        app: news-service
    spec:
      containers:
        - name: news-service
          image: anurag2911/news-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_URI
            - name: NATS_URL
              value: "nats://nats:4222"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /news-api/news
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /news-api/news
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
              
---
apiVersion: v1
kind: Service
metadata:
  name: news-service
  namespace: default
spec:
  selector:
    app: news-service
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
