apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-service
spec:
  template:
    spec:
      containers:
      - name: news-service
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        env:
        - name: LOG_LEVEL
          value: "debug"
        - name: NEWS_FETCH_INTERVAL_HOURS
          value: "1"  # More frequent fetching in dev
