apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: scrollfeed-dev

resources:
- ../../../base/news-service

patchesStrategicMerge:
- deployment-patch.yaml

namePrefix: dev-

commonLabels:
  environment: dev
  
images:
- name: anurag2911/news-service
  newTag: dev-latest

replicas:
- name: news-service
  count: 1
