apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  labels:
    app: analytics-service
    component: microservice
    part-of: scrollfeed
spec:
  selector:
    app: analytics-service
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
