apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scrollfeed-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: scrollfeed
  source:
    repoURL: https://github.com/justscrollorg/scrollfeed-services
    targetRevision: HEAD
    path: argocd/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
