apiVersion: v1
kind: Service
metadata:
  name: articles-service
  labels:
    app: articles-service
spec:
  selector:
    app: articles-service
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
