---
apiVersion: v1
kind: Namespace
metadata:
  name: nats-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  namespace: nats-system
  labels:
    app: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
      - name: nats
        image: nats:2.10-alpine
        ports:
        - containerPort: 4222
          name: client
        - containerPort: 8222
          name: monitoring
        args:
        - "-js"
        - "-m"
        - "8222"
        - "--store_dir=/data"
        - "--max_file_store=1GB"
        - "--max_mem_store=256MB"
        volumeMounts:
        - name: nats-data
          mountPath: /data
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 8222
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8222
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: nats-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: nats-system
spec:
  selector:
    app: nats
  ports:
  - name: client
    port: 4222
    targetPort: 4222
  - name: monitoring
    port: 8222
    targetPort: 8222
  type: ClusterIP
