apiVersion: apps/v1
kind: Deployment
metadata:
  name: memes-service
  namespace: default
  labels:
    app: memes-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: memes-service
  template:
    metadata:
      labels:
        app: memes-service
    spec:
      containers:
      - name: memes-service
        image: justscroll/memes-service:latest
        imagePullPolicy: Always
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_URI
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /memes/trending
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /memes/trending
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: memes-service
  namespace: default
spec:
  selector:
    app: memes-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
