apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-service
  template:
    metadata:
      labels:
        app: video-service
    spec:
      containers:
        - name: video-service
          image: anurag2911/video-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: YOUTUBE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: youtube-api-secret
                  key: YOUTUBE_API_KEY
            - name: MONGO_URI
              value: "mongodb://mongodb.mongo:27017"
            - name: NATS_URL
              value: "nats://nats.nats-system:4222"
            - name: FETCH_INTERVAL_HOURS
              value: "6"
            - name: RATE_LIMIT_SECONDS
              value: "3"
            - name: WORKER_COUNT
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: video-service
  namespace: default
spec:
  selector:
    app: video-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
