name: Build and Push Microservices

on:
  workflow_dispatch:
    inputs:
      services:
        description: 'Services to build (comma-separated or "all")'
        required: false
        default: 'all'
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [video-service, news-service, news-fetcher-service, analytics-service, memes-service]

    steps:
      - name: Check if service should be built
        id: should_build
        run: |
          if [[ "${{ github.event.inputs.services }}" == "all" ]] || [[ "${{ github.event.inputs.services }}" == *"${{ matrix.service }}"* ]]; then
            echo "build=true" >> $GITHUB_OUTPUT
          else
            echo "build=false" >> $GITHUB_OUTPUT
          fi

      - name: Checkout code
        if: steps.should_build.outputs.build == 'true'
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        if: steps.should_build.outputs.build == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: steps.should_build.outputs.build == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate image tag
        if: steps.should_build.outputs.build == 'true'
        id: tag
        run: |
          echo "IMAGE_TAG=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
          echo "FULL_TAG=justscroll/${{ matrix.service }}:${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        if: steps.should_build.outputs.build == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: |
            justscroll/${{ matrix.service }}:latest
            justscroll/${{ matrix.service }}:${{ steps.tag.outputs.IMAGE_TAG }}

      - name: Update deployment manifests
        if: steps.should_build.outputs.build == 'true'
        run: |
          # Update production deployment
          sed -i "s|justscroll/${{ matrix.service }}:.*|justscroll/${{ matrix.service }}:${{ steps.tag.outputs.IMAGE_TAG }}|g" k8s/base/${{ matrix.service }}/deployment.yaml
          
          # Update dev deployment if it exists
          if [ -f "k8s/overlays/dev/${{ matrix.service }}/deployment.yaml" ]; then
            sed -i "s|justscroll/${{ matrix.service }}:.*|justscroll/${{ matrix.service }}:${{ steps.tag.outputs.IMAGE_TAG }}|g" k8s/overlays/dev/${{ matrix.service }}/deployment.yaml
          fi

      - name: Commit and push changes
        if: steps.should_build.outputs.build == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add k8s/
          git diff --staged --quiet || (git commit -m "Update ${{ matrix.service }} image to ${{ steps.tag.outputs.IMAGE_TAG }}" && git push)
